# Generated by Django 5.2.1 on 2025-05-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0013_videocamera_short_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='embed_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='videocamera',
            name='description',
            field=models.CharField(default='Lotte Harper is live at localhost', max_length=1000),
        ),
    ]
