# Generated by Django 5.2.1 on 2025-05-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0014_videocamera_embed_logo_alter_videocamera_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocamera',
            name='mimetype',
            field=models.CharField(default='mp4; codecs="avc1.42E01E, mp4a.40.2"', max_length=100),
        ),
    ]
