# Generated by Django 5.2.1 on 2025-05-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0015_videocamera_mimetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocamera',
            name='stream',
        ),
        migrations.AddField(
            model_name='videocamera',
            name='livestream',
            field=models.BooleanField(default=False),
        ),
    ]
